version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: shipment-tracking-api-dev
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - API_PREFIX=${API_PREFIX:-/api/v1}
      - TRUST_PROXY=${TRUST_PROXY:-loopback, linklocal, uniquelocal}
      # Captcha Services
      - CAPTCHA_SOLVER_API_KEY=${CAPTCHA_SOLVER_API_KEY:-}
      # Google AI
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      # Browserless
      - BROWSERLESS_API_TOKEN=${BROWSERLESS_API_TOKEN:-}
      # Api key for accessing the API
      - X_API_KEY=${X_API_KEY:-}
    volumes:
      # Hot reload support
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
      - ./nodemon.json:/app/nodemon.json
      # Persist logs and node_modules
      - ./logs:/app/logs
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  node_modules:
